"""Add cover image, start date, and end date to trip

Revision ID: 4a4460f5599d
Revises: 486934fe8bdd
Create Date: 2025-03-23 17:56:29.004743

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a4460f5599d'
down_revision = '486934fe8bdd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trip', schema=None) as batch_op:
        batch_op.alter_column('image_filenames',
               existing_type=sa.TEXT(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trip', schema=None) as batch_op:
        batch_op.alter_column('image_filenames',
               existing_type=sa.TEXT(),
               nullable=False)

    # ### end Alembic commands ###
