"""empty message

Revision ID: 486934fe8bdd
Revises: 
Create Date: 2025-03-23 17:47:44.099931

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '486934fe8bdd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('checklist_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('trip', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cover_image', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('start_date', sa.Date(), nullable=False))
        batch_op.add_column(sa.Column('end_date', sa.Date(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trip', schema=None) as batch_op:
        batch_op.drop_column('end_date')
        batch_op.drop_column('start_date')
        batch_op.drop_column('cover_image')

    op.drop_table('checklist_item')
    # ### end Alembic commands ###
